server:
  port: 8604
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
       include: '*'
    web:
     exposure:
      include: '*'
      base-path: /actuator
    cors:
      allowed-origins: true
      enabled-by-default: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8602/eureka/, http://localhost:8602/eureka/
