spring:
  jpa:
      generate-ddl: true
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
        #none, validate, update, create, and create-drop
        ddl-auto: create
      show-sql: true